<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .title { font-size: 24px; font-weight: bold; text-transform: uppercase; margin-bottom: 5px; }
        .subtitle { font-size: 14px; color: #666; }
        .info-grid { width: 100%; margin-bottom: 30px; font-size: 13px; }
        .info-label { font-weight: bold; color: #555; width: 120px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 11px; }
        th { background-color: #f5f5f5; border: 1px solid #ddd; padding: 10px; text-align: left; text-transform: uppercase; }
        td { border: 1px solid #ddd; padding: 8px; }
        .total-row { background-color: #fafafa; font-weight: bold; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
        .score-cell { text-align: center; font-family: 'Courier', monospace; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Academic Semester Report</div>
        <div class="subtitle">{{ $class->subject->name ?? 'Class' }} • {{ $assignment->academic_year }} Semester {{ $assignment->semester }}</div>
    </div>

    <table class="info-grid">
        <tr>
            <td class="info-label">Department:</td><td>{{ $department }}</td>
            <td class="info-label">Major/Group:</td><td>{{ $major }} ({{ $class->groups->pluck('name')->join(', ') }})</td>
        </tr>
        <tr>
            <td class="info-label">Teacher:</td><td>{{ $class->teacher->user->name ?? 'N/A' }}</td>
            <td class="info-label">Class ID:</td><td>#{{ $class->id }}</td>
        </tr>
        <tr>
            <td class="info-label">Export Date:</td><td>{{ now()->format('M d, Y H:i') }}</td>
            <td class="info-label">Avg. Attendance:</td><td>{{ round($stats['avg_rate'], 1) }}%</td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th style="width: 30px;">#</th>
                <th>Student Name</th>
                <th style="width: 80px;">Student ID</th>
                <th style="width: 50px; text-align:center;">Att %</th>
                <th style="width: 40px; text-align:center;">Att(20)</th>
                <th style="width: 40px; text-align:center;">Mid(15)</th>
                <th style="width: 40px; text-align:center;">Asgn(15)</th>
                <th style="width: 40px; text-align:center;">Final(50)</th>
                <th style="width: 50px; text-align:center;">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $student)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $student['name'] }}</td>
                <td>{{ $student['code'] }}</td>
                <td style="text-align:center;">{{ $student['rate'] }}%</td>
                <td class="score-cell">{{ $student['att_score'] }}</td>
                <td class="score-cell">{{ $student['midterm'] }}</td>
                <td class="score-cell">{{ $student['assignment'] }}</td>
                <td class="score-cell">{{ $student['final'] }}</td>
                <td class="score-cell" style="background:#f9f9f9;">{{ $student['total'] }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="8" style="text-align:right; padding: 10px;">CLASS AVERAGE SCORE:</td>
                <td style="text-align:center; padding: 10px;">{{ round($stats['avg_total'], 2) }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by Academic Grading System • Confidential Administrative Document
    </div>
</body>
</html>
